stages:
  - test
  - docs

"Julia release, OS X":
  tags:
    - osx
  script:
    - curl -s -o setup-julia https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/setup-julia && source setup-julia release
    - julia --depwarn=no -e "symlink(\"$CI_PROJECT_DIR\", Pkg.dir(\"$PKG_NAME\")); Pkg.resolve(); Pkg.build(\"$PKG_NAME\"); Pkg.test(\"$PKG_NAME\")"
    - bash setup-julia clean

"Julia release, Linux (amd64)":
  tags:
    - linux
    - amd64
  script:
    - curl -s -o setup-julia https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/setup-julia && source setup-julia release
    - julia --depwarn=no -e "symlink(\"$CI_PROJECT_DIR\", Pkg.dir(\"$PKG_NAME\")); Pkg.resolve(); Pkg.build(\"$PKG_NAME\"); Pkg.test(\"$PKG_NAME\")"
    - bash setup-julia clean

"Julia release, Linux (i386)":
  tags:
    - linux
    - i386
  script:
    - curl -s -o setup-julia https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/setup-julia && source setup-julia release
    - julia --depwarn=no -e "symlink(\"$CI_PROJECT_DIR\", Pkg.dir(\"$PKG_NAME\")); Pkg.resolve(); Pkg.build(\"$PKG_NAME\"); Pkg.test(\"$PKG_NAME\")"
    - bash setup-julia clean

"Julia nightly, OS X":
  stage: test
  tags:
    - osx
  script:
    - curl -s -o setup-julia https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/setup-julia && source setup-julia nightly
    - julia --depwarn=no -e "symlink(\"$CI_PROJECT_DIR\", Pkg.dir(\"$PKG_NAME\")); Pkg.resolve(); Pkg.build(\"$PKG_NAME\"); Pkg.test(\"$PKG_NAME\")"
    - bash setup-julia clean


"Julia nightly, Linux (amd64)":
  stage: test
  tags:
    - linux
    - amd64
  script:
    - curl -s -o setup-julia https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/setup-julia && source setup-julia nightly
    - julia --depwarn=no -e "symlink(\"$CI_PROJECT_DIR\", Pkg.dir(\"$PKG_NAME\")); Pkg.resolve(); Pkg.build(\"$PKG_NAME\"); Pkg.test(\"$PKG_NAME\")"
    - bash setup-julia clean

"Julia nightly, Linux (i386)":
  stage: test
  tags:
    - linux
    - i386
  script:
    - curl -s -o setup-julia https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/setup-julia && source setup-julia nightly
    - julia --depwarn=no -e "symlink(\"$CI_PROJECT_DIR\", Pkg.dir(\"$PKG_NAME\")); Pkg.resolve(); Pkg.build(\"$PKG_NAME\"); Pkg.test(\"$PKG_NAME\")"
    - bash setup-julia clean

"Documentation":
  stage: docs
  tags:
    - docs
  only:
    - master
    - develop
    - docs
    - tags  # special keyword for all tags
  script:
    - curl -s -o setup-julia https://gitlab.invenia.ca/infrastructure/gitlab-ci-helper/raw/master/setup-julia && source setup-julia nightly
    - julia --depwarn=no -e "symlink(\"$CI_PROJECT_DIR\", Pkg.dir(\"$PKG_NAME\")); Pkg.resolve(); Pkg.checkout("Documenter"); Pkg.build(\"$PKG_NAME\");"
    - julia --depwarn=no -e "cd(Pkg.dir(\"$PKG_NAME\", "docs")); include("make.jl"); run(`mkdocs build`)"
    - julia --depwarn=no -e "const DOCS_DIR = joinpath("/mnt", "docs", \"$CI_PROJECT_NAMESPACE\", \"$CI_PROJECT_NAME\", \"$CI_BUILD_REF_NAME\"); mkpath(DOCS_DIR); cp(Pkg.dir(\"$PKG_NAME\", "docs", "site"), DOCS_DIR; remove_destination=true, follow_symlinks=true)"
    - bash setup-julia clean
